# VM options: -Dspring.profiles.active=dev

spring:
  datasource:
    url: jdbc:postgresql://localhost:8301/txn-asset-db
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      default:
        partitions: 1
        replicas: 1

server:
  port: 8300