spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/liquibase-changelog.xml
  kafka:
    producer:
      topic:
        default:
          partitions: 10
          replicas: 3
        prices:
          name: prices
          partitions: ${spring.kafka.producer.default.partitions}
          replicas: ${spring.kafka.producer.default.replicas}
        assets:
          name: assets
          partitions: ${spring.kafka.producer.default.partitions}
          replicas: ${spring.kafka.producer.default.replicas}