# VM options: -Dspring.profiles.active=dev

spring:
  datasource:
    url: jdbc:postgresql://localhost:8301/txn-asset-api-db
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8300